export const ALTA_DE_LINEA = 'ALTA_DE_LINEA';
export const ALTA_DE_CLIENTE = 'ALTA_DE_CLIENTE';
export const DESEMBOLSO = 'DESEMBOLSO';

export const ALTA_DE_CUENTA_CLIENTE = 'ALTA_DE_CUENTA_CLIENTE';
export const DESBLOQUEAR_CUENTA = 'DESBLOQUEAR_CUENTA';
