export const campoRequerido = () => 'Campo requerido';
export const captcha = () => 'La verificación caducó. Vuelve a marcar la casilla de verificación.';
export const longitudMaxima = ({ max }) => `Longitud máxima: ${max} caracteres`;
export const longitudMinima = ({ min }) => `Longitud mínima: ${min} caracteres`;
export const campoInvalido = () => 'Campo inválido';
export const lowerUpperCase = () => 'Debe tener mínimo 1 letra mayúscula y 1 minúscula';
export const noConsecutives = () => 'Sin números consecutivos';
export const minOneNumber = () => 'Debe tener mínimo 1 número';
export const seleccionOpcion = () => 'Selecciona una opción';
export const ingreseOpcion = () => 'Ingrese una opción';
export const numeroInvalido = () => 'Número telefónico inválido';
export const correoInvalido = () => 'Correo inválido';
export const rfcInvalido = () => 'RFC inválido';
export const sinCaracteresEspeciales = () => 'Sin caracteres especiales o acentos';
export const aceptarTerminos = () => 'Debe aceptar los términos';
export const declararTerminos = () => 'Debe declarar los términos';
export const codigoPostalInvalido = () => 'Código postal inválido';
export const numeroMinimo = ({ min }) => `El número debe ser mayor o igual a ${min}`;
export const numeroMaximo = ({ max }) => `El número debe ser menor o igual a ${max}`;
export const clabeNumeroCuentaInvalido = () => 'CLABE o número de cuenta inválido';
export const ciecInvalida = () => 'Ciec inválido';
