export const DATO_PERSONA = 'DATO_PERSONA';

export const DATO_PERSONA_CONFIRMAR_CORREO = 'DATO_PERSONA_CONFIRMAR_CORREO';
export const DATO_EMPRESA = 'DATO_EMPRESA';
export const DATOS_EMPRESA_LEGALEX = 'DATOS_EMPRESA_LEGALEX';
export const MOTOR = 'EN_ESPERA_RESULTADO_MOTOR';
export const OFERTA = 'OFERTA';
export const DOCUMENTACION = 'DOCUMENTACION';
export const DOCUMENTACION_INCOMPLETO = 'DOCUMENTACION_INCOMPLETO';
export const DOCUMENTACION_BIOMETRICOS = 'DOCUMENTACION_BIOMETRICOS';
export const DOCUMENTACION_OBLIGADO_SOLIDARIO = 'DOCUMENTACION_OBLIGADO_SOLIDARIO';
export const OBLIGADO_SOLIDARIO = 'OBLIGADO_SOLIDARIO';
