apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: bsi-cred-pyme-web
  name: cm-bsi-cred-pyme-web
data:
  application.properties: |
    # ===================================================================
    # Propiedades generales de la aplicación
    # ===================================================================
    # Puerto por defecto donde escucha el servidor
    # server.port=8081
  NEXT_PUBLIC_API_BANCOPPEL_PYME_HOSTNAME: bsi-cred-pyme-service-bsi-cr-pyme-web-stg.obe8.bancoppel-dev.openshiftapps.com
  NEXT_PUBLIC_API_BANCOPPEL_PYME_HOST: https://bsi-cred-pyme-service-bsi-cr-pyme-web-stg.obe8.bancoppel-dev.openshiftapps.com/api
  NEXT_PUBLIC_PYME_HOSTNAME: http://bsi-cred-pyme-web-bsi-cr-pyme-web-stg.obe8.bancoppel-dev.openshiftapps.com/api/proxy
