export const NEXT_STEP_DATOS_PERSONALES = 'NEXT_STEP_DATOS_PERSONALES';
export const NEXT_STEP_DATOS_EMPRESA = 'NEXT_STEP_DATOS_EMPRESA';
export const RESET_DATOS_PERSONALES = 'RESET_DATOS_PERSONALES';

export const UPDATE_DATA_SIMULADOR = 'UPDATE_DATA_SIMULADOR';
export const UPDATE_SHOW_RESULT_SIMULADOR = 'UPDATE_SHOW_RESULT_SIMULADOR';

export const CHANGE_PAGE = 'CHANGE_PAGE';
export const RESET_CHANGE_PAGE = 'RESET_CHANGE_PAGE';

export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const RESET = 'RESET';
