export const NEXT_STEP_DATOS_PERSONALES = 'NEXT_STEP_DATOS_PERSONALES';
export const NEXT_STEP_DATOS_EMPRESA = 'NEXT_STEP_DATOS_EMPRESA';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const RESET = 'RESET';
