- apiVersion: v1
    kind: BuildConfig
    metadata:
      name: '${NAME}'
      labels:
        app: '${NAME}'
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: '${NAME}:latest'
      postCommit: {}
      resources:
        limits:
          cpu: 1200m
          memory: 2Gi
        requests:
          cpu: 1000m
          memory: 1Gi
      source:
        contextDir: /
        git:
          uri: '${SOURCE_REPOSITORY_URL}'
          ref: '${SOURCE_REPOSITORY_REF}'
        sourceSecret:
          name: '${SOURCE_SECRET}'
        type: Git
      strategy:
        sourceStrategy:
          env:
            - name: GIT_SSL_NO_VERIFY
              value: ${GIT_SSL_NO_VERIFY}
          from:
            kind: DockerImage
            name: "ubi8/nodejs-14"
          type: Source
      triggers:
        - github:
            secret: '${GITHUB_WEBHOOK_SECRET}'
          type: GitHub
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
    status:
      lastVersion: 0