- apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: '${NAME}'
      labels:
        app: '${NAME}'
    spec:
      template:
        spec:
          containers:
            - image: '${NAME}:latest'
              name: '${NAME}'
              securityContext:
                privileged: false
              ports:
                - containerPort: 3000
                  name: http
                  protocol: TCP
              resources: {}
        metadata:
          labels:
            app: '${NAME}'
      replicas: 1
      selector:
        app: '${NAME}'
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - '${NAME}'
            from:
              kind: ImageStreamTag
              name: '${NAME}:latest'