- apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      ports:
        - name: http
          port: 3000
      selector:
        app: ${NAME}
      type: ClusterIP
      resources: {}

    - apiVersion: v1
      kind: Route
      metadata:
        labels:
          app: ${NAME}
        name: ${NAME}
      spec:
        port:
          targetPort: 3000
        to:
          kind: Service
          name: ${NAME}
          weight: 100
        wildcardPolicy: None